# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
      # Every Wednesday 05h25m UTC
      - cron: '25 5 * * 3'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
  
      # Setup Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Setup Clava
      - name: Update/install Clava
        run: |
           cd ..
           mkdir -p clava
           cd clava
           pwd
           # Delete file before downloading
           rm clava-update -f
           wget specs.fe.up.pt/tools/clava/clava-update -nv
           chmod +x clava-update
           ./clava-update

      # Setup Kadabra
      - name: Update/install Kadabra
        run: |
          cd ..
          mkdir -p kadabra
          cd kadabra
          pwd
          # Delete file before downloading
          rm kadabra.zip -f
          wget specs.fe.up.pt/tools/kadabra.zip -nv
          unzip -q -o kadabra.zip


      # Run Clava tests
      - name: Clava tests 
        run: |
          # cd ${{ github.workspace }}
          ../clava/clava -c config-grouping.clava
          ../clava/clava -c config-relations.clava
          # ../clava/clava -c config-repos-cppunit.clava        # Parsing of cppunit not working
          # ../clava/clava -c config-repos-cppunit-fixed.clava  # Parsing of cppunit not working
          # ../clava/clava -c config-repos-cppunit-latest.clava # Parsing of cppunit not working          

      # Run Kadabra tests
      - name: Kadabra tests 
        run: |
          # cd ${{ github.workspace }}
          java -jar ../kadabra/kadabra.jar -c config-relations.kadabra                    
          # This example takes a long time to execute
          #java -jar ../kadabra/kadabra.jar -c config-repos-ant.kadabra                    
          java -jar ../kadabra/kadabra.jar -c config-repos-awt.kadabra                  
          java -jar ../kadabra/kadabra.jar -c config-repos-jhotdraw.kadabra                
          java -jar ../kadabra/kadabra.jar -c config-repos-junit.kadabra                 
          java -jar ../kadabra/kadabra.jar -c config-repos-pmart-01-quickuml.kadabra
          java -jar ../kadabra/kadabra.jar -c config-repos-pmart-02-lexi.kadabra
          java -jar ../kadabra/kadabra.jar -c config-repos-pmart-03-jrefactory.kadabra
          # This example is throwing a parser exception, spoon.compiler.ModelBuildingException: The type CalcLexer is already defined
          #java -jar ../kadabra/kadabra.jar -c config-repos-pmart-04-netbeans.kadabra
          java -jar ../kadabra/kadabra.jar -c config-repos-pmart-05-junit.kadabra
          java -jar ../kadabra/kadabra.jar -c config-repos-pmart-06-jhotdraw.kadabra
          java -jar ../kadabra/kadabra.jar -c config-repos-pmart-08-mapperxml.kadabra
          java -jar ../kadabra/kadabra.jar -c config-repos-pmart-10-nutch.kadabra
          java -jar ../kadabra/kadabra.jar -c config-repos-pmart-11-pmd.kadabra
          
